Demere question data model
dev-mission/bulga pull request #13
Opened 2021-04-15 02:55 UTC by DBoog415

2021-04-20 23:31 UTC, chucklui requested changes
The resource table should not be here. It should only be the question table. Please change!

2021-04-20 23:54 UTC, w-disheng requested changes
Demere, your first commit was correct, why did you push the wrong database you had already for resources? the new commit you push which "Demere resource-data-creation" was wrong. Please do git reset --hard HEAD ~1 and push again thanks

2021-04-21 05:28 UTC, w-disheng approved these changes

2021-04-21 05:35 UTC, chucklui approved these changes
looks good

2021-04-21 05:35 UTC, merged