Chuck newuser setup pages flow
dev-mission/bulga pull request #21
Opened 2021-05-08 02:35 UTC by chucklui

need help on connecting submit button on register page to the setup page

2021-05-11 02:28 UTC, francisli requested changes
@chucklui I left a comment on the code in this PR to show where you can change where the app goes after the register is complete.

Also, you need to merge the latest code from main branch onto your branch and resolve the conflict that github is showing.

2021-05-11 02:28 UTC, francisli commented on client/src/Register.js
> +      history.push('/login', { flash: 'Your account has been created!' });
@chucklui it's on this line that the Register component navigates to a new page after the register is complete, by "pushing" a new page path onto the browser history.

Right now, it is going to the /login path after register is complete, where do you want it to go next?

2021-05-12 02:06 UTC, w-disheng approved these changes

2021-05-12 02:52 UTC, francisli approved these changes

2021-05-12 02:53 UTC, merged